services:
    example.extension:
        class: App\Extension\ExampleExtension
        public: false
        tags:
            - { name: api_platform.doctrine.orm.query_extension.collection, priority: 9 }
            - { name: api_platform.doctrine.orm.query_extension.item }


    extension.user:
        class: App\Extension\UserExtension
        public: false
        tags:
            - { name: api_platform.doctrine.orm.query_extension.collection, priority: 9 }
            - { name: api_platform.doctrine.orm.query_extension.item }
        arguments:
            - '@security.token_storage'