fos_user:
    db_driver:     orm
    firewall_name: main
    service:
        mailer: fos_user.mailer.twig_swift
    from_email:
        address:        "%mailer_address%"
        sender_name:    "%mailer_sender_name%"
    user_class:    App\Entity\User
    group:
        group_class:   Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager