vich_uploader:
    db_driver: orm
    storage:   gaufrette
    mappings:
        uploaded_image:
            uri_prefix:         /uploads/images
            upload_destination: media_fs
            namer:              vich_uploader.namer_uniqid
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true